# Generated by Django 4.0 on 2022-01-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalproduct',
            table='product_history',
        ),
    ]
