# Generated by Django 4.0 on 2022-01-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_historicalproduct_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalproduct',
            table=None,
        ),
    ]
